/* ============================================================
   NOVA SKILLS — Course Data
   Single source of truth for all course information
   12 Academies · 100+ Courses · Real pricing from branding PDF
   ============================================================ */

const NS_COURSES = [

  /* =========================================================
     1. DIGITAL MARKETING ACADEMY
  ========================================================= */
  {
    id: 'dm-professional',
    slug: 'ai-digital-marketing-professional',
    academy: 'Digital Marketing Academy',
    academyId: 'digital-marketing',
    icon: '📊',
    color: 'linear-gradient(135deg, #FF6B00, #FF9A3C)',
    name: 'AI Digital Marketing Professional',
    shortDesc: 'Master Google Ads, SEO & GEO, Meta Ads, Social Media, Content & AI-powered marketing from scratch.',
    fullDesc: 'A comprehensive 3-month programme covering every aspect of modern digital marketing — from SEO and Google Ads to Meta Ads, AI marketing automation and performance analytics. Designed for beginners and career switchers.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Hybrid', level: 'Beginner',
    price: 17499, originalPrice: 49999,
    rating: 4.8, reviews: 312,
    students: 1840,
    liveProjects: 10, certificate: true, placementSupport: true,
    tools: ['Google Ads', 'Meta Ads Manager', 'SEMrush', 'GA4', 'ChatGPT', 'Canva', 'HubSpot'],
    curriculum: [
      { module: 'Module 1', title: 'Digital Marketing Fundamentals', lessons: 8 },
      { module: 'Module 2', title: 'SEO & GEO (AI Search Optimisation)', lessons: 12 },
      { module: 'Module 3', title: 'Google Ads & SEM', lessons: 10 },
      { module: 'Module 4', title: 'Meta Ads (Facebook & Instagram)', lessons: 10 },
      { module: 'Module 5', title: 'Social Media Marketing', lessons: 8 },
      { module: 'Module 6', title: 'Content Marketing & Strategy', lessons: 6 },
      { module: 'Module 7', title: 'Email & Affiliate Marketing', lessons: 6 },
      { module: 'Module 8', title: 'Performance Marketing & Analytics', lessons: 8 },
      { module: 'Module 9', title: 'AI Marketing Tools & Automation', lessons: 8 },
      { module: 'Module 10', title: 'Capstone Campaign Project', lessons: 6 },
    ],
    tags: ['popular', 'placement'],
    featured: true,
  },
  {
    id: 'dm-mastery',
    slug: 'ai-digital-marketing-mastery',
    academy: 'Digital Marketing Academy',
    academyId: 'digital-marketing',
    icon: '📊',
    color: 'linear-gradient(135deg, #FF6B00, #8B5CF6)',
    name: 'AI Digital Marketing Mastery',
    shortDesc: 'Complete 6-month mastery: all 15 modules, live campaigns, AI automation and freelancing skills.',
    fullDesc: 'The most comprehensive digital marketing programme in India. All 15 modules including SEO, Google Ads, Meta Ads, Email, Affiliate, E-commerce, YouTube, LinkedIn, AI Automation and Freelancing — in one 6-month power programme.',
    duration: '6 Months', durationMonths: 6,
    mode: 'Hybrid', level: 'Advanced',
    price: 31499, originalPrice: 89999,
    rating: 4.9, reviews: 198,
    students: 920,
    liveProjects: 20, certificate: true, placementSupport: true,
    tools: ['Google Ads', 'Meta Ads', 'SEMrush', 'Ahrefs', 'GA4', 'HubSpot', 'Mailchimp', 'n8n', 'ChatGPT'],
    curriculum: [
      { module: 'Phase 1', title: 'Digital Marketing Foundation (Weeks 1–4)', lessons: 20 },
      { module: 'Phase 2', title: 'Paid Advertising Mastery (Weeks 5–10)', lessons: 24 },
      { module: 'Phase 3', title: 'Content & Social Media (Weeks 11–14)', lessons: 16 },
      { module: 'Phase 4', title: 'E-commerce & Analytics (Weeks 15–18)', lessons: 16 },
      { module: 'Phase 5', title: 'AI Marketing & Automation (Weeks 19–22)', lessons: 16 },
      { module: 'Phase 6', title: 'Freelancing & Agency Skills (Weeks 23–24)', lessons: 12 },
    ],
    tags: ['bestseller', 'popular', 'placement'],
    featured: true,
  },
  {
    id: 'seo-geo',
    slug: 'seo-geo-ai-search-optimisation',
    academy: 'Digital Marketing Academy',
    academyId: 'digital-marketing',
    icon: '📊', color: 'linear-gradient(135deg, #FF6B00, #FF9A3C)',
    name: 'SEO & GEO (AI Search Optimisation)',
    shortDesc: 'Master traditional SEO and next-gen GEO — optimise for AI-powered search engines.',
    fullDesc: 'The only course in India teaching both traditional SEO and Generative Engine Optimisation (GEO) — the future of search visibility in AI-driven search engines like Google AI Mode and Perplexity.',
    duration: '2 Months', durationMonths: 2,
    mode: 'Online', level: 'Intermediate',
    price: 6999, originalPrice: 19999,
    rating: 4.7, reviews: 145,
    students: 876,
    liveProjects: 5, certificate: true, placementSupport: false,
    tools: ['SEMrush', 'Ahrefs', 'Google Search Console', 'ChatGPT', 'Screaming Frog'],
    curriculum: [
      { module: 'Module 1', title: 'SEO Fundamentals & Technical SEO', lessons: 10 },
      { module: 'Module 2', title: 'On-Page & Off-Page Optimisation', lessons: 8 },
      { module: 'Module 3', title: 'Keyword Research & Content Strategy', lessons: 6 },
      { module: 'Module 4', title: 'GEO — Generative Engine Optimisation', lessons: 8 },
      { module: 'Module 5', title: 'AI-Powered SEO Tools & Automation', lessons: 6 },
    ],
    tags: ['trending'],
    featured: false,
  },
  {
    id: 'google-ads',
    slug: 'google-ads-course',
    academy: 'Digital Marketing Academy', academyId: 'digital-marketing',
    icon: '📊', color: 'linear-gradient(135deg, #FF6B00, #FF9A3C)',
    name: 'Google Ads', shortDesc: 'From zero to certified Google Ads expert. Search, Display, Shopping, YouTube & Performance Max.',
    fullDesc: 'A focused 2-month deep-dive into Google Ads ecosystem covering all campaign types, bidding strategies, conversion tracking and Google Ads certification.',
    duration: '2 Months', durationMonths: 2,
    mode: 'Online', level: 'Beginner',
    price: 6999, originalPrice: 19999,
    rating: 4.6, reviews: 211, students: 1240,
    liveProjects: 4, certificate: true, placementSupport: false,
    tools: ['Google Ads', 'Google Analytics 4', 'Google Tag Manager', 'Google Merchant Centre'],
    curriculum: [
      { module: 'Module 1', title: 'Google Ads Account Setup & Structure', lessons: 6 },
      { module: 'Module 2', title: 'Search Campaigns & Keyword Mastery', lessons: 8 },
      { module: 'Module 3', title: 'Display, Video & Shopping Campaigns', lessons: 8 },
      { module: 'Module 4', title: 'Performance Max & Smart Campaigns', lessons: 6 },
      { module: 'Module 5', title: 'Tracking, Analytics & Optimisation', lessons: 8 },
    ],
    tags: ['popular'],
    featured: false,
  },
  {
    id: 'meta-ads',
    slug: 'meta-ads-facebook-instagram',
    academy: 'Digital Marketing Academy', academyId: 'digital-marketing',
    icon: '📊', color: 'linear-gradient(135deg, #FF6B00, #FF9A3C)',
    name: 'Meta Ads (Facebook & Instagram)', shortDesc: 'Master Facebook and Instagram advertising — from campaign setup to ROAS optimisation.',
    fullDesc: 'Complete Meta Ads training covering Facebook & Instagram advertising, audience targeting, creative strategy, retargeting and campaign optimisation for maximum ROI.',
    duration: '2 Months', durationMonths: 2,
    mode: 'Online', level: 'Beginner',
    price: 6999, originalPrice: 19999,
    rating: 4.7, reviews: 188, students: 1100,
    liveProjects: 4, certificate: true, placementSupport: false,
    tools: ['Meta Business Suite', 'Meta Ads Manager', 'Meta Pixel', 'Canva'],
    curriculum: [
      { module: 'Module 1', title: 'Meta Ads Ecosystem & Account Setup', lessons: 6 },
      { module: 'Module 2', title: 'Audience Research & Targeting', lessons: 8 },
      { module: 'Module 3', title: 'Campaign Types & Creative Strategy', lessons: 8 },
      { module: 'Module 4', title: 'Retargeting & Lookalike Audiences', lessons: 6 },
      { module: 'Module 5', title: 'ROAS Optimisation & Scaling', lessons: 8 },
    ],
    tags: ['popular'],
    featured: false,
  },

  /* =========================================================
     2. AI ACADEMY
  ========================================================= */
  {
    id: 'ai-mastery',
    slug: 'ai-mastery-program',
    academy: 'AI Academy', academyId: 'ai',
    icon: '🤖', color: 'linear-gradient(135deg, #0599a8, #75d766)',
    name: 'AI Mastery Program',
    shortDesc: 'Complete AI: ChatGPT, Prompt Engineering, AI Agents, n8n Automation, AI Coding & more.',
    fullDesc: 'The most comprehensive AI skills programme in India. In 6 months, you will master ChatGPT, Prompt Engineering, AI for Business, AI Agents, n8n Workflow Automation, AI Video, Image Generation, AI Coding and real-world AI projects.',
    duration: '6 Months', durationMonths: 6,
    mode: 'Hybrid', level: 'Beginner',
    price: 27999, originalPrice: 79999,
    rating: 4.9, reviews: 284, students: 1560,
    liveProjects: 20, certificate: true, placementSupport: true,
    tools: ['ChatGPT', 'Claude', 'Gemini', 'Midjourney', 'n8n', 'Make.com', 'Cursor AI', 'Sora'],
    curriculum: [
      { module: 'Phase 1', title: 'AI Fundamentals & ChatGPT Mastery', lessons: 14 },
      { module: 'Phase 2', title: 'Prompt Engineering & AI Content Creation', lessons: 14 },
      { module: 'Phase 3', title: 'AI for Business & Productivity', lessons: 12 },
      { module: 'Phase 4', title: 'AI Image & Video Generation', lessons: 10 },
      { module: 'Phase 5', title: 'AI Automation with n8n & Make', lessons: 12 },
      { module: 'Phase 6', title: 'AI Agents & AI Coding Projects', lessons: 14 },
    ],
    tags: ['bestseller', 'popular', 'placement', 'trending'],
    featured: true,
  },
  {
    id: 'ai-productivity',
    slug: 'ai-productivity-professional',
    academy: 'AI Academy', academyId: 'ai',
    icon: '🤖', color: 'linear-gradient(135deg, #0599a8, #75d766)',
    name: 'AI Productivity Professional',
    shortDesc: 'Use AI tools to 10x your work output: ChatGPT, Prompt Engineering, AI Automation & AI Research.',
    fullDesc: 'A focused 3-month programme teaching professionals how to leverage AI tools to dramatically increase productivity, automate repetitive tasks, and deliver better results in less time.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Online', level: 'Beginner',
    price: 13999, originalPrice: 39999,
    rating: 4.8, reviews: 176, students: 980,
    liveProjects: 10, certificate: true, placementSupport: false,
    tools: ['ChatGPT', 'Perplexity', 'Notion AI', 'Make.com', 'Zapier', 'Claude'],
    curriculum: [
      { module: 'Module 1', title: 'AI Fundamentals & ChatGPT', lessons: 8 },
      { module: 'Module 2', title: 'Prompt Engineering', lessons: 8 },
      { module: 'Module 3', title: 'AI for Content & Research', lessons: 8 },
      { module: 'Module 4', title: 'AI Workflow Automation', lessons: 10 },
      { module: 'Module 5', title: 'AI for Business & Projects', lessons: 8 },
    ],
    tags: ['popular'],
    featured: false,
  },
  {
    id: 'ai-automation-n8n',
    slug: 'ai-automation-n8n',
    academy: 'AI Academy', academyId: 'ai',
    icon: '🤖', color: 'linear-gradient(135deg, #0599a8, #75d766)',
    name: 'AI Automation with n8n',
    shortDesc: 'Build powerful no-code AI automation workflows with n8n, Make.com and AI APIs.',
    fullDesc: 'Learn to build sophisticated AI-powered automation workflows using n8n and Make.com. Connect APIs, automate business processes and build AI agents without writing complex code.',
    duration: '— Months', durationMonths: 1.5,
    mode: 'Online', level: 'Intermediate',
    price: 9099, originalPrice: 24999,
    rating: 4.8, reviews: 98, students: 540,
    liveProjects: 6, certificate: true, placementSupport: false,
    tools: ['n8n', 'Make.com', 'OpenAI API', 'Webhook.site', 'Airtable'],
    curriculum: [
      { module: 'Module 1', title: 'n8n Fundamentals & Workflow Basics', lessons: 8 },
      { module: 'Module 2', title: 'API Connections & Data Manipulation', lessons: 8 },
      { module: 'Module 3', title: 'AI Integration with LLMs', lessons: 8 },
      { module: 'Module 4', title: 'Building AI Agents & Bots', lessons: 8 },
    ],
    tags: ['trending'],
    featured: false,
  },

  /* =========================================================
     3. KIDS TECH ACADEMY
  ========================================================= */
  {
    id: 'kids-mastery',
    slug: 'future-tech-kids-mastery',
    academy: 'Kids Tech Academy', academyId: 'kids',
    icon: '👨‍💻', color: 'linear-gradient(135deg, #EC4899, #8B5CF6)',
    name: 'Future Tech Kids Mastery',
    shortDesc: 'Complete 6-month tech journey for kids: Scratch, Python, Web Design, AI, Robotics & Game Design.',
    fullDesc: 'A comprehensive 6-month programme designed for children aged 8–16, covering Scratch, Python, Web Design, Canva, AI Basics, Animation, Game Design, Minecraft Education and Robotics — all in a fun, engaging format.',
    duration: '6 Months', durationMonths: 6,
    mode: 'Hybrid', level: 'Beginner',
    price: 17499, originalPrice: 49999,
    rating: 4.9, reviews: 124, students: 680,
    liveProjects: 15, certificate: true, placementSupport: false,
    tools: ['Scratch', 'Python', 'HTML/CSS', 'Canva', 'Arduino', 'Minecraft Education'],
    curriculum: [
      { module: 'Phase 1', title: 'Computer Basics & Scratch Programming', lessons: 12 },
      { module: 'Phase 2', title: 'Python for Kids', lessons: 12 },
      { module: 'Phase 3', title: 'Web Design & Canva', lessons: 10 },
      { module: 'Phase 4', title: 'AI Basics & AI Art', lessons: 8 },
      { module: 'Phase 5', title: 'Game Design & Animation', lessons: 10 },
      { module: 'Phase 6', title: 'Robotics & Final Project', lessons: 10 },
    ],
    tags: ['popular'],
    featured: true,
  },
  {
    id: 'young-coders',
    slug: 'young-coders-program',
    academy: 'Kids Tech Academy', academyId: 'kids',
    icon: '👨‍💻', color: 'linear-gradient(135deg, #EC4899, #8B5CF6)',
    name: 'Young Coders Program',
    shortDesc: 'Step-by-step coding journey for kids aged 8–14: Scratch, Python, coding logic and first projects.',
    fullDesc: 'A structured 3-month programme introducing children to coding through Scratch, Python basics, logical thinking and creative problem solving — resulting in working apps and games.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Offline', level: 'Beginner',
    price: 10499, originalPrice: 29999,
    rating: 4.8, reviews: 86, students: 420,
    liveProjects: 6, certificate: true, placementSupport: false,
    tools: ['Scratch', 'Python', 'Code.org'],
    curriculum: [
      { module: 'Module 1', title: 'Computer Basics & Scratch', lessons: 10 },
      { module: 'Module 2', title: 'Scratch Advanced Projects', lessons: 8 },
      { module: 'Module 3', title: 'Python for Kids — Basics', lessons: 10 },
      { module: 'Module 4', title: 'First Apps & Games', lessons: 8 },
    ],
    tags: [],
    featured: false,
  },

  /* =========================================================
     4. DESIGN ACADEMY
  ========================================================= */
  {
    id: 'creative-design',
    slug: 'creative-design-mastery',
    academy: 'Design Academy', academyId: 'design',
    icon: '🎨', color: 'linear-gradient(135deg, #8B5CF6, #EC4899)',
    name: 'Creative Design Mastery',
    shortDesc: 'Photoshop, Illustrator, Figma, InDesign, UI Design, Brand Identity, Logo & Packaging — all in 6 months.',
    fullDesc: 'India\'s most comprehensive graphic design programme. Master the complete Adobe Creative Suite plus Figma, brand identity design, logo design, packaging design and UI/UX — building a professional portfolio along the way.',
    duration: '6 Months', durationMonths: 6,
    mode: 'Hybrid', level: 'Beginner',
    price: 27999, originalPrice: 79999,
    rating: 4.9, reviews: 267, students: 1420,
    liveProjects: 18, certificate: true, placementSupport: true,
    tools: ['Photoshop', 'Illustrator', 'Figma', 'InDesign', 'Adobe Express', 'Canva Pro'],
    curriculum: [
      { module: 'Phase 1', title: 'Design Principles & Photoshop Mastery', lessons: 14 },
      { module: 'Phase 2', title: 'Illustrator & Vector Design', lessons: 12 },
      { module: 'Phase 3', title: 'Brand Identity & Logo Design', lessons: 10 },
      { module: 'Phase 4', title: 'UI Design with Figma', lessons: 10 },
      { module: 'Phase 5', title: 'Packaging & Print Design', lessons: 8 },
      { module: 'Phase 6', title: 'Portfolio & Real Client Projects', lessons: 10 },
    ],
    tags: ['bestseller', 'popular', 'placement'],
    featured: true,
  },
  {
    id: 'graphic-design-pro',
    slug: 'graphic-design-professional',
    academy: 'Design Academy', academyId: 'design',
    icon: '🎨', color: 'linear-gradient(135deg, #8B5CF6, #EC4899)',
    name: 'Graphic Design Professional',
    shortDesc: 'Photoshop, Illustrator, Canva Pro and brand design in 3 months. Build a job-ready design portfolio.',
    fullDesc: 'A focused 3-month design programme covering Photoshop, Illustrator, Canva Pro, Adobe Express and brand design fundamentals — resulting in a professional portfolio for job applications or freelancing.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Hybrid', level: 'Beginner',
    price: 17499, originalPrice: 49999,
    rating: 4.7, reviews: 198, students: 1050,
    liveProjects: 8, certificate: true, placementSupport: true,
    tools: ['Photoshop', 'Illustrator', 'Canva Pro', 'Adobe Express'],
    curriculum: [
      { module: 'Module 1', title: 'Design Principles & Colour Theory', lessons: 8 },
      { module: 'Module 2', title: 'Photoshop Mastery', lessons: 12 },
      { module: 'Module 3', title: 'Illustrator & Vector Design', lessons: 10 },
      { module: 'Module 4', title: 'Canva Pro & Social Media Design', lessons: 8 },
      { module: 'Module 5', title: 'Portfolio Building', lessons: 6 },
    ],
    tags: ['popular', 'placement'],
    featured: false,
  },

  /* =========================================================
     5. VIDEO & MOTION ACADEMY
  ========================================================= */
  {
    id: 'motion-mastery',
    slug: 'motion-graphics-mastery',
    academy: 'Video & Motion Academy', academyId: 'video',
    icon: '🎬', color: 'linear-gradient(135deg, #EF4444, #F97316)',
    name: 'Motion Graphics Mastery',
    shortDesc: 'Premiere Pro, After Effects, Motion Graphics, DaVinci Resolve & Professional Cinematography in 6 months.',
    fullDesc: 'Master the complete video production stack: Adobe Premiere Pro, After Effects, Motion Graphics, DaVinci Resolve colour grading, camera operation, cinematography and professional video editing for films, ads and social media.',
    duration: '6 Months', durationMonths: 6,
    mode: 'Hybrid', level: 'Intermediate',
    price: 27999, originalPrice: 79999,
    rating: 4.8, reviews: 187, students: 890,
    liveProjects: 16, certificate: true, placementSupport: true,
    tools: ['Premiere Pro', 'After Effects', 'DaVinci Resolve', 'Audition', 'Cinema 4D'],
    curriculum: [
      { module: 'Phase 1', title: 'Video Editing Fundamentals & Premiere Pro', lessons: 12 },
      { module: 'Phase 2', title: 'Motion Graphics with After Effects', lessons: 14 },
      { module: 'Phase 3', title: 'Colour Grading with DaVinci Resolve', lessons: 8 },
      { module: 'Phase 4', title: 'Audio Design & Podcast Editing', lessons: 6 },
      { module: 'Phase 5', title: 'Camera Operation & Cinematography', lessons: 8 },
      { module: 'Phase 6', title: 'Showreel & Commercial Projects', lessons: 8 },
    ],
    tags: ['popular', 'placement'],
    featured: true,
  },
  {
    id: 'video-pro',
    slug: 'professional-video-editing',
    academy: 'Video & Motion Academy', academyId: 'video',
    icon: '🎬', color: 'linear-gradient(135deg, #EF4444, #F97316)',
    name: 'Professional Video Editing',
    shortDesc: 'Master Premiere Pro, DaVinci Resolve and Reels editing in 3 months.',
    fullDesc: 'A focused 3-month video editing programme for beginners and social media creators. Master Premiere Pro, DaVinci Resolve, Reels editing and audio syncing — create professional content from day one.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Online', level: 'Beginner',
    price: 17499, originalPrice: 49999,
    rating: 4.7, reviews: 134, students: 720,
    liveProjects: 8, certificate: true, placementSupport: true,
    tools: ['Premiere Pro', 'DaVinci Resolve', 'CapCut', 'Audition'],
    curriculum: [
      { module: 'Module 1', title: 'Editing Basics & Premiere Pro', lessons: 10 },
      { module: 'Module 2', title: 'Colour Grading & Audio', lessons: 8 },
      { module: 'Module 3', title: 'Reels, Shorts & Social Editing', lessons: 8 },
      { module: 'Module 4', title: 'Client Project & Portfolio', lessons: 6 },
    ],
    tags: ['popular'],
    featured: false,
  },

  /* =========================================================
     6. 3D ACADEMY
  ========================================================= */
  {
    id: 'archviz-mastery',
    slug: 'architectural-visualisation-mastery',
    academy: '3D Academy', academyId: '3d',
    icon: '🏗️', color: 'linear-gradient(135deg, #10B981, #059669)',
    name: 'Architectural Visualisation Mastery',
    shortDesc: '3ds Max, V-Ray, Blender, Cinema 4D, Twinmotion & Unreal Engine for ArchViz — 6 months.',
    fullDesc: 'The complete architectural visualisation programme covering 3ds Max, V-Ray rendering, Blender, Cinema 4D with Redshift, Twinmotion and Unreal Engine for ArchViz. Build a stunning portfolio of architectural renders.',
    duration: '6 Months', durationMonths: 6,
    mode: 'Hybrid', level: 'Intermediate',
    price: 34999, originalPrice: 99999,
    rating: 4.8, reviews: 76, students: 380,
    liveProjects: 12, certificate: true, placementSupport: true,
    tools: ['3ds Max', 'V-Ray', 'Blender', 'Cinema 4D', 'Redshift', 'Twinmotion', 'Unreal Engine'],
    curriculum: [
      { module: 'Phase 1', title: '3D Basics & 3ds Max Fundamentals', lessons: 12 },
      { module: 'Phase 2', title: 'V-Ray Rendering & Lighting', lessons: 12 },
      { module: 'Phase 3', title: 'Blender & Open-Source 3D', lessons: 10 },
      { module: 'Phase 4', title: 'Cinema 4D + Redshift', lessons: 10 },
      { module: 'Phase 5', title: 'Twinmotion & Real-Time ArchViz', lessons: 8 },
      { module: 'Phase 6', title: 'Unreal Engine for ArchViz', lessons: 10 },
    ],
    tags: ['placement'],
    featured: true,
  },
  {
    id: '3d-viz-pro',
    slug: '3d-visualisation-professional',
    academy: '3D Academy', academyId: '3d',
    icon: '🏗️', color: 'linear-gradient(135deg, #10B981, #059669)',
    name: '3D Visualisation Professional',
    shortDesc: '3ds Max, V-Ray and Blender in 3 months. Build professional 3D renders and visualisations.',
    fullDesc: 'A focused 3-month 3D visualisation programme covering 3ds Max, V-Ray rendering, lighting and Blender for beginners — resulting in professional-quality 3D renders.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Offline', level: 'Beginner',
    price: 20999, originalPrice: 59999,
    rating: 4.7, reviews: 52, students: 280,
    liveProjects: 6, certificate: true, placementSupport: true,
    tools: ['3ds Max', 'V-Ray', 'Blender'],
    curriculum: [
      { module: 'Module 1', title: '3D Fundamentals & 3ds Max', lessons: 10 },
      { module: 'Module 2', title: 'Modelling & Materials', lessons: 10 },
      { module: 'Module 3', title: 'V-Ray Lighting & Rendering', lessons: 10 },
      { module: 'Module 4', title: 'Portfolio Projects', lessons: 6 },
    ],
    tags: [],
    featured: false,
  },

  /* =========================================================
     7. NO-CODE WEB DEVELOPMENT ACADEMY
  ========================================================= */
  {
    id: 'ecommerce-mastery',
    slug: 'ecommerce-website-mastery',
    academy: 'No-Code Web Academy', academyId: 'nocode',
    icon: '🌐', color: 'linear-gradient(135deg, #F59E0B, #EF4444)',
    name: 'E-Commerce Website Mastery',
    shortDesc: 'WordPress, WooCommerce, Shopify, Webflow & Framer — build and launch complete e-commerce websites.',
    fullDesc: 'Build professional e-commerce websites without code using WordPress, WooCommerce, Shopify, Webflow and Framer. Learn payment gateway integration, SEO, product management and website launch.',
    duration: '6 Months', durationMonths: 6,
    mode: 'Hybrid', level: 'Beginner',
    price: 27999, originalPrice: 79999,
    rating: 4.8, reviews: 142, students: 760,
    liveProjects: 10, certificate: true, placementSupport: true,
    tools: ['WordPress', 'WooCommerce', 'Shopify', 'Webflow', 'Framer', 'Elementor Pro'],
    curriculum: [
      { module: 'Phase 1', title: 'WordPress & Elementor Pro', lessons: 12 },
      { module: 'Phase 2', title: 'WooCommerce E-Commerce', lessons: 10 },
      { module: 'Phase 3', title: 'Shopify Store Building', lessons: 10 },
      { module: 'Phase 4', title: 'Webflow & Framer', lessons: 10 },
      { module: 'Phase 5', title: 'SEO, Payment Gateway & Launch', lessons: 8 },
      { module: 'Phase 6', title: 'Freelancing & Client Projects', lessons: 8 },
    ],
    tags: ['popular', 'placement'],
    featured: true,
  },
  {
    id: 'nocode-web-pro',
    slug: 'no-code-website-professional',
    academy: 'No-Code Web Academy', academyId: 'nocode',
    icon: '🌐', color: 'linear-gradient(135deg, #F59E0B, #EF4444)',
    name: 'No-Code Website Professional',
    shortDesc: 'Build beautiful professional websites using WordPress, Elementor and Webflow — no coding required.',
    fullDesc: 'A focused 3-month programme for building professional websites using WordPress, Elementor Pro, Webflow and Framer — without writing a single line of code.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Online', level: 'Beginner',
    price: 17499, originalPrice: 49999,
    rating: 4.7, reviews: 116, students: 640,
    liveProjects: 6, certificate: true, placementSupport: true,
    tools: ['WordPress', 'Elementor Pro', 'Webflow', 'Framer'],
    curriculum: [
      { module: 'Module 1', title: 'Web Design Fundamentals', lessons: 6 },
      { module: 'Module 2', title: 'WordPress & Elementor', lessons: 10 },
      { module: 'Module 3', title: 'Webflow & Framer', lessons: 8 },
      { module: 'Module 4', title: 'SEO & Website Launch', lessons: 6 },
    ],
    tags: ['popular'],
    featured: false,
  },

  /* =========================================================
     8. PROGRAMMING ACADEMY
  ========================================================= */
  {
    id: 'fullstack-foundation',
    slug: 'full-stack-programming-foundation',
    academy: 'Programming Academy', academyId: 'programming',
    icon: '💻', color: 'linear-gradient(135deg, #2563EB, #0599a8)',
    name: 'Full Stack Programming Foundation',
    shortDesc: 'HTML, CSS, Bootstrap, JavaScript, Python, SQL, Git & REST APIs — complete developer roadmap in 6 months.',
    fullDesc: 'A comprehensive 6-month programming foundation covering HTML, CSS, Bootstrap, JavaScript, Python, SQL, Git and REST APIs — giving you everything needed to start working as a junior full-stack developer or freelancer.',
    duration: '6 Months', durationMonths: 6,
    mode: 'Hybrid', level: 'Beginner',
    price: 31499, originalPrice: 89999,
    rating: 4.9, reviews: 198, students: 980,
    liveProjects: 16, certificate: true, placementSupport: true,
    tools: ['VS Code', 'GitHub', 'Python', 'JavaScript', 'MySQL', 'Postman'],
    curriculum: [
      { module: 'Phase 1', title: 'HTML, CSS & Responsive Design', lessons: 12 },
      { module: 'Phase 2', title: 'Bootstrap & JavaScript Fundamentals', lessons: 14 },
      { module: 'Phase 3', title: 'Python Programming & OOP', lessons: 12 },
      { module: 'Phase 4', title: 'Databases & SQL', lessons: 10 },
      { module: 'Phase 5', title: 'Git, GitHub & REST APIs', lessons: 8 },
      { module: 'Phase 6', title: 'Portfolio Projects & Job Prep', lessons: 10 },
    ],
    tags: ['bestseller', 'popular', 'placement'],
    featured: true,
  },
  {
    id: 'python-developer',
    slug: 'python-developer-professional',
    academy: 'Programming Academy', academyId: 'programming',
    icon: '💻', color: 'linear-gradient(135deg, #2563EB, #0599a8)',
    name: 'Python Developer Professional',
    shortDesc: 'Python, OOP, SQL, Git and REST APIs in 3 months. Land your first developer job.',
    fullDesc: 'A focused 3-month Python programme covering Python basics, OOP, SQL, GitHub and REST APIs — equipping you to work as a Python developer, data analyst or backend developer.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Online', level: 'Beginner',
    price: 17499, originalPrice: 49999,
    rating: 4.7, reviews: 154, students: 760,
    liveProjects: 8, certificate: true, placementSupport: true,
    tools: ['Python', 'VS Code', 'MySQL', 'Git', 'Postman'],
    curriculum: [
      { module: 'Module 1', title: 'Python Fundamentals', lessons: 10 },
      { module: 'Module 2', title: 'OOP & Advanced Python', lessons: 10 },
      { module: 'Module 3', title: 'SQL & Database Management', lessons: 8 },
      { module: 'Module 4', title: 'APIs & Real Projects', lessons: 8 },
    ],
    tags: ['popular', 'placement'],
    featured: false,
  },

  /* =========================================================
     9. CREATOR ACADEMY
  ========================================================= */
  {
    id: 'youtube-mastery',
    slug: 'youtube-growth-mastery',
    academy: 'Creator Academy', academyId: 'creator',
    icon: '🎥', color: 'linear-gradient(135deg, #FF6B00, #EC4899)',
    name: 'YouTube Growth Mastery',
    shortDesc: 'Complete YouTube channel strategy: content planning, SEO, editing, thumbnails, monetisation & growth.',
    fullDesc: 'From zero to a monetised YouTube channel in 6 months. Master channel setup, content strategy, scripting, video editing, thumbnail design, YouTube SEO, community building and monetisation strategies.',
    duration: '6 Months', durationMonths: 6,
    mode: 'Online', level: 'Beginner',
    price: 24499, originalPrice: 69999,
    rating: 4.8, reviews: 134, students: 760,
    liveProjects: 12, certificate: true, placementSupport: false,
    tools: ['YouTube Studio', 'Premiere Pro', 'Canva', 'TubeBuddy', 'VidIQ'],
    curriculum: [
      { module: 'Phase 1', title: 'Channel Setup & Content Strategy', lessons: 8 },
      { module: 'Phase 2', title: 'Scripting & Video Production', lessons: 10 },
      { module: 'Phase 3', title: 'Video Editing & Thumbnails', lessons: 10 },
      { module: 'Phase 4', title: 'YouTube SEO & Algorithm', lessons: 8 },
      { module: 'Phase 5', title: 'Community Building & Shorts', lessons: 8 },
      { module: 'Phase 6', title: 'Monetisation & Scaling', lessons: 8 },
    ],
    tags: ['popular', 'trending'],
    featured: true,
  },
  {
    id: 'content-creator-pro',
    slug: 'content-creator-professional',
    academy: 'Creator Academy', academyId: 'creator',
    icon: '🎥', color: 'linear-gradient(135deg, #FF6B00, #EC4899)',
    name: 'Content Creator Professional',
    shortDesc: 'YouTube, Instagram, Blogging, Podcasting & Personal Branding in 3 months.',
    fullDesc: 'A 3-month programme teaching you to build a strong personal brand across YouTube, Instagram, Blog and Podcast — with content planning, creation, editing and monetisation strategies.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Online', level: 'Beginner',
    price: 13999, originalPrice: 39999,
    rating: 4.7, reviews: 98, students: 580,
    liveProjects: 6, certificate: true, placementSupport: false,
    tools: ['YouTube Studio', 'Canva', 'CapCut', 'Anchor FM'],
    curriculum: [
      { module: 'Module 1', title: 'Personal Branding & Niche', lessons: 6 },
      { module: 'Module 2', title: 'YouTube & Instagram Growth', lessons: 10 },
      { module: 'Module 3', title: 'Blogging & Podcasting', lessons: 8 },
      { module: 'Module 4', title: 'Monetisation & Influencer Marketing', lessons: 8 },
    ],
    tags: [],
    featured: false,
  },

  /* =========================================================
     10. OFFICE PRODUCTIVITY
  ========================================================= */
  {
    id: 'biz-productivity',
    slug: 'business-productivity-mastery',
    academy: 'Office Productivity', academyId: 'office',
    icon: '📋', color: 'linear-gradient(135deg, #0599a8, #2563EB)',
    name: 'Business Productivity Mastery',
    shortDesc: 'Excel, PowerPoint, Tally Prime, Google Workspace, Notion, ClickUp & Microsoft Copilot.',
    fullDesc: 'Master all essential office productivity tools in 3 months: Advanced Excel, PowerPoint, Tally Prime with GST, Google Workspace, Notion, ClickUp, Trello and Microsoft Copilot for AI-powered productivity.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Hybrid', level: 'Beginner',
    price: 10499, originalPrice: 29999,
    rating: 4.7, reviews: 178, students: 1240,
    liveProjects: 6, certificate: true, placementSupport: true,
    tools: ['Microsoft Excel', 'PowerPoint', 'Tally Prime', 'Google Workspace', 'Notion', 'ClickUp', 'Microsoft Copilot'],
    curriculum: [
      { module: 'Module 1', title: 'Excel & Advanced Excel', lessons: 10 },
      { module: 'Module 2', title: 'PowerPoint & Presentations', lessons: 6 },
      { module: 'Module 3', title: 'Tally Prime with GST', lessons: 8 },
      { module: 'Module 4', title: 'Google Workspace & Sheets', lessons: 6 },
      { module: 'Module 5', title: 'Notion, ClickUp, Trello & Copilot', lessons: 6 },
    ],
    tags: ['popular'],
    featured: false,
  },
  {
    id: 'office-pro',
    slug: 'office-productivity-professional',
    academy: 'Office Productivity', academyId: 'office',
    icon: '📋', color: 'linear-gradient(135deg, #0599a8, #2563EB)',
    name: 'Office Productivity Professional',
    shortDesc: 'Excel, PowerPoint, Word, Google Workspace & Notion in 2 months. Get office-ready fast.',
    fullDesc: 'A compact 2-month programme covering all essential office tools — Microsoft Office suite, Google Workspace, Notion and ClickUp — for office professionals, students and job seekers.',
    duration: '2 Months', durationMonths: 2,
    mode: 'Offline', level: 'Beginner',
    price: 6999, originalPrice: 19999,
    rating: 4.6, reviews: 212, students: 1560,
    liveProjects: 4, certificate: true, placementSupport: false,
    tools: ['Microsoft Word', 'Excel', 'PowerPoint', 'Google Workspace', 'Notion'],
    curriculum: [
      { module: 'Module 1', title: 'Microsoft Word & PowerPoint', lessons: 6 },
      { module: 'Module 2', title: 'Excel & Google Sheets', lessons: 8 },
      { module: 'Module 3', title: 'Google Workspace', lessons: 6 },
      { module: 'Module 4', title: 'Notion & ClickUp', lessons: 6 },
    ],
    tags: ['popular'],
    featured: false,
  },

  /* =========================================================
     11. COMMUNICATION ACADEMY
  ========================================================= */
  {
    id: 'business-english',
    slug: 'business-english-personality-development',
    academy: 'Communication Academy', academyId: 'communication',
    icon: '💬', color: 'linear-gradient(135deg, #75d766, #0599a8)',
    name: 'Business English & Personality Development',
    shortDesc: 'Spoken English, Business Communication, Presentation Skills, Interview Skills & Confidence.',
    fullDesc: 'A transformative 6-month programme combining advanced spoken English, business communication, email writing, presentation skills, group discussion, interview preparation, and complete personality development.',
    duration: '6 Months', durationMonths: 6,
    mode: 'Hybrid', level: 'Beginner',
    price: 17499, originalPrice: 49999,
    rating: 4.8, reviews: 156, students: 980,
    liveProjects: 8, certificate: true, placementSupport: true,
    tools: ['Zoom', 'Grammarly', 'ChatGPT'],
    curriculum: [
      { module: 'Phase 1', title: 'English Grammar & Vocabulary', lessons: 10 },
      { module: 'Phase 2', title: 'Spoken English & Fluency', lessons: 12 },
      { module: 'Phase 3', title: 'Business Communication & Email Writing', lessons: 8 },
      { module: 'Phase 4', title: 'Presentation & Public Speaking', lessons: 8 },
      { module: 'Phase 5', title: 'Interview Skills & GD', lessons: 8 },
      { module: 'Phase 6', title: 'Leadership & Confidence Building', lessons: 8 },
    ],
    tags: ['popular', 'placement'],
    featured: true,
  },
  {
    id: 'spoken-english-pro',
    slug: 'professional-spoken-english',
    academy: 'Communication Academy', academyId: 'communication',
    icon: '💬', color: 'linear-gradient(135deg, #75d766, #0599a8)',
    name: 'Professional Spoken English',
    shortDesc: 'From basic to fluent spoken English in 3 months. Master pronunciation, fluency and business vocabulary.',
    fullDesc: 'A focused 3-month programme for developing fluent spoken English — covering pronunciation, grammar, vocabulary, sentence formation, daily conversation and business English.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Hybrid', level: 'Beginner',
    price: 10499, originalPrice: 29999,
    rating: 4.7, reviews: 198, students: 1380,
    liveProjects: 4, certificate: true, placementSupport: false,
    tools: ['Zoom', 'Grammarly'],
    curriculum: [
      { module: 'Module 1', title: 'Grammar & Vocabulary Foundation', lessons: 8 },
      { module: 'Module 2', title: 'Pronunciation & Fluency', lessons: 8 },
      { module: 'Module 3', title: 'Business Conversation & Email', lessons: 8 },
      { module: 'Module 4', title: 'Presentation & Interview Skills', lessons: 8 },
    ],
    tags: ['popular'],
    featured: false,
  },

  /* =========================================================
     12. CAREER ACADEMY
  ========================================================= */
  {
    id: 'freelancing-mastery',
    slug: 'freelancing-mastery',
    academy: 'Career Academy', academyId: 'career',
    icon: '💼', color: 'linear-gradient(135deg, #011731, #0599a8)',
    name: 'Freelancing Mastery',
    shortDesc: 'Fiverr, Upwork, Proposal Writing, Client Acquisition & building a 6-figure freelance business.',
    fullDesc: 'Start and scale your freelance career in 3 months. Master Fiverr and Upwork profile optimisation, proposal writing, client acquisition, pricing, payment processing and scaling to ₹1 lakh+ per month.',
    duration: '3 Months', durationMonths: 3,
    mode: 'Online', level: 'Intermediate',
    price: 13999, originalPrice: 39999,
    rating: 4.8, reviews: 124, students: 840,
    liveProjects: 6, certificate: true, placementSupport: false,
    tools: ['Fiverr', 'Upwork', 'Notion', 'Calendly', 'Razorpay'],
    curriculum: [
      { module: 'Module 1', title: 'Freelancing Fundamentals & Mindset', lessons: 6 },
      { module: 'Module 2', title: 'Fiverr & Upwork Profile Mastery', lessons: 8 },
      { module: 'Module 3', title: 'Proposal Writing & Client Acquisition', lessons: 8 },
      { module: 'Module 4', title: 'Pricing, Contracts & Payments', lessons: 6 },
      { module: 'Module 5', title: 'Scaling Your Freelance Business', lessons: 8 },
    ],
    tags: ['popular', 'trending'],
    featured: true,
  },
  {
    id: 'career-launch',
    slug: 'career-launch-program',
    academy: 'Career Academy', academyId: 'career',
    icon: '💼', color: 'linear-gradient(135deg, #011731, #0599a8)',
    name: 'Career Launch Program',
    shortDesc: 'Resume Building, LinkedIn Optimisation, Portfolio, Interview Prep & Job Search strategy.',
    fullDesc: 'A 2-month intensive programme for fresh graduates and career switchers — covering resume writing, LinkedIn optimisation, portfolio development, interview preparation and job search strategy.',
    duration: '2 Months', durationMonths: 2,
    mode: 'Online', level: 'Beginner',
    price: 9099, originalPrice: 24999,
    rating: 4.8, reviews: 176, students: 1240,
    liveProjects: 4, certificate: true, placementSupport: true,
    tools: ['LinkedIn', 'Canva', 'Grammarly', 'Notion'],
    curriculum: [
      { module: 'Module 1', title: 'Resume Building & ATS Optimisation', lessons: 6 },
      { module: 'Module 2', title: 'LinkedIn Profile & Personal Branding', lessons: 6 },
      { module: 'Module 3', title: 'Portfolio Development', lessons: 6 },
      { module: 'Module 4', title: 'Interview Preparation & Job Search', lessons: 8 },
    ],
    tags: ['popular', 'placement'],
    featured: false,
  },
];

/* Academy metadata for filters and display */
const NS_ACADEMIES = [
  { id: 'digital-marketing', name: 'Digital Marketing Academy', icon: '📊', color: 'linear-gradient(135deg,#FF6B00,#FF9A3C)' },
  { id: 'ai', name: 'AI Academy', icon: '🤖', color: 'linear-gradient(135deg,#0599a8,#75d766)' },
  { id: 'kids', name: 'Kids Tech Academy', icon: '👨‍💻', color: 'linear-gradient(135deg,#EC4899,#8B5CF6)' },
  { id: 'design', name: 'Design Academy', icon: '🎨', color: 'linear-gradient(135deg,#8B5CF6,#EC4899)' },
  { id: 'video', name: 'Video & Motion Academy', icon: '🎬', color: 'linear-gradient(135deg,#EF4444,#F97316)' },
  { id: '3d', name: '3D Academy', icon: '🏗️', color: 'linear-gradient(135deg,#10B981,#059669)' },
  { id: 'nocode', name: 'No-Code Web Academy', icon: '🌐', color: 'linear-gradient(135deg,#F59E0B,#EF4444)' },
  { id: 'programming', name: 'Programming Academy', icon: '💻', color: 'linear-gradient(135deg,#2563EB,#0599a8)' },
  { id: 'creator', name: 'Creator Academy', icon: '🎥', color: 'linear-gradient(135deg,#FF6B00,#EC4899)' },
  { id: 'office', name: 'Office Productivity', icon: '📋', color: 'linear-gradient(135deg,#0599a8,#2563EB)' },
  { id: 'communication', name: 'Communication Academy', icon: '💬', color: 'linear-gradient(135deg,#75d766,#0599a8)' },
  { id: 'career', name: 'Career Academy', icon: '💼', color: 'linear-gradient(135deg,#011731,#0599a8)' },
];

/* Blog posts data */
const NS_BLOG_POSTS = [
  {
    id: 1, slug: 'ai-jobs-india-2026',
    title: 'Top 15 AI Jobs in India 2026: Salaries, Skills & How to Get Hired',
    excerpt: 'AI is not replacing jobs — it\'s creating them. Discover the highest-paying AI roles in India, what skills they require, and how Nova Skills can get you there in 6 months.',
    category: 'Career Advice',
    author: 'Sanya Puri', authorRole: 'Lead AI Trainer',
    readTime: 8, date: '2026-07-20',
    tags: ['AI', 'Career', 'Jobs', 'India'],
    featured: true, trending: true,
    image: null,
  },
  {
    id: 2, slug: 'digital-marketing-salary-india',
    title: 'Digital Marketing Salary in India 2026: Complete Guide',
    excerpt: 'From freshers to senior marketers — everything you need to know about digital marketing salaries across India\'s top cities, industries and job roles.',
    category: 'Digital Marketing',
    author: 'Arjun Kapoor', authorRole: 'Head of Digital Marketing',
    readTime: 6, date: '2026-07-15',
    tags: ['Digital Marketing', 'Salary', 'Career'],
    featured: false, trending: true,
    image: null,
  },
  {
    id: 3, slug: 'learn-graphic-design-beginner-guide',
    title: 'How to Learn Graphic Design from Scratch: Complete 2026 Guide',
    excerpt: 'Whether you\'re a complete beginner or want to go professional, this step-by-step guide covers tools, techniques, portfolio building and landing your first design client.',
    category: 'Design',
    author: 'Rajan Verma', authorRole: 'Senior Design Trainer',
    readTime: 10, date: '2026-07-10',
    tags: ['Graphic Design', 'Beginner', 'Photoshop', 'Figma'],
    featured: false, trending: false,
    image: null,
  },
  {
    id: 4, slug: 'freelancing-fiverr-india-guide',
    title: 'How to Earn ₹1 Lakh/Month Freelancing on Fiverr in India',
    excerpt: 'A practical, no-fluff guide to building a 6-figure freelance income on Fiverr from India — niche selection, profile optimisation, proposals and scaling strategies.',
    category: 'Freelancing',
    author: 'Priya Kumar', authorRole: 'Freelancing Success Coach',
    readTime: 7, date: '2026-07-05',
    tags: ['Freelancing', 'Fiverr', 'Income'],
    featured: false, trending: true,
    image: null,
  },
  {
    id: 5, slug: 'n8n-ai-automation-beginners',
    title: 'n8n AI Automation for Beginners: Build Your First AI Workflow',
    excerpt: 'Step-by-step tutorial to build a powerful AI automation workflow using n8n — no coding required. Automate repetitive tasks, connect APIs and build AI agents.',
    category: 'AI & Technology',
    author: 'Sanya Puri', authorRole: 'Lead AI Trainer',
    readTime: 12, date: '2026-07-01',
    tags: ['n8n', 'AI Automation', 'No-Code'],
    featured: false, trending: false,
    image: null,
  },
  {
    id: 6, slug: 'youtube-channel-monetise-2026',
    title: 'How to Start & Monetise a YouTube Channel in 2026: Step-by-Step',
    excerpt: 'From zero subscribers to YouTube Partner — a complete, updated guide to growing a successful YouTube channel with the latest 2026 algorithm changes and strategies.',
    category: 'Content Creation',
    author: 'Mohammed Tahir', authorRole: 'Creator Academy Lead',
    readTime: 9, date: '2026-06-25',
    tags: ['YouTube', 'Creator', 'Monetisation'],
    featured: false, trending: false,
    image: null,
  },
  {
    id: 7, slug: 'chatgpt-prompts-marketing',
    title: '50 ChatGPT Prompts That Will Transform Your Marketing',
    excerpt: 'Stop wasting time on generic AI outputs. These 50 expert-crafted prompts will give you high-converting ad copy, SEO content, email sequences and campaign strategies.',
    category: 'AI & Technology',
    author: 'Arjun Kapoor', authorRole: 'Head of Digital Marketing',
    readTime: 5, date: '2026-06-18',
    tags: ['ChatGPT', 'AI', 'Marketing', 'Prompts'],
    featured: false, trending: false,
    image: null,
  },
  {
    id: 8, slug: 'kids-coding-benefits-india',
    title: 'Why Every Indian Child Should Learn to Code Before Age 12',
    excerpt: 'The future belongs to children who understand technology. Discover why coding education is critical for Indian kids and how parents can get their child started.',
    category: 'Kids Education',
    author: 'Dr. Sunita Rao', authorRole: 'Kids Tech Academy Director',
    readTime: 6, date: '2026-06-12',
    tags: ['Kids', 'Coding', 'Education', 'Parents'],
    featured: false, trending: false,
    image: null,
  },
  {
    id: 9, slug: 'python-vs-javascript-2026',
    title: 'Python vs JavaScript in 2026: Which Should You Learn First?',
    excerpt: 'The ultimate comparison for beginners — Python or JavaScript? We break down career paths, job market demand, salary potential and which language suits your goals.',
    category: 'Programming',
    author: 'Vikram Nair', authorRole: 'Programming Academy Lead',
    readTime: 8, date: '2026-06-08',
    tags: ['Python', 'JavaScript', 'Programming'],
    featured: false, trending: false,
    image: null,
  },
];
