/**
 * Enterprise Role-Based Access Control (RBAC) Permission Matrix
 * Configurable Roles & Permissions definitions
 */

export const PERMISSIONS = {
  VIEW_LEADS: 'view_leads',
  CREATE_LEADS: 'create_leads',
  EDIT_LEADS: 'edit_leads',
  DELETE_LEADS: 'delete_leads',
  ASSIGN_COUNSELLOR: 'assign_counsellor',

  VIEW_REPORTS: 'view_reports',
  GENERATE_AI_REPORTS: 'generate_ai_reports',
  USE_AI_STUDIO: 'use_ai_studio',

  MANAGE_PAYMENTS: 'manage_payments',
  MANAGE_BATCHES: 'manage_batches',
  MANAGE_STUDENTS: 'manage_students',
  MANAGE_STAFF: 'manage_staff',
  MANAGE_WEBSITE: 'manage_website',

  MANAGE_AI_SETTINGS: 'manage_ai_settings',
  MANAGE_API_KEYS: 'manage_api_keys',
  MANAGE_USERS: 'manage_users',
  MANAGE_ROLES: 'manage_roles'
};

export const ROLES = {
  SUPER_ADMIN: 'Super Admin',
  ADMIN: 'Admin',
  ADMISSION_MANAGER: 'Admission Manager',
  COUNSELLOR: 'Counsellor',
  RECEPTIONIST: 'Receptionist',
  TRAINER: 'Trainer',
  ACCOUNTANT: 'Accountant',
  MARKETING_EXECUTIVE: 'Marketing Executive',
  STUDENT: 'Student',
  PARENT: 'Parent',
  GUEST: 'Guest'
};

export const ROLE_PERMISSION_MATRIX = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_LEADS, PERMISSIONS.CREATE_LEADS, PERMISSIONS.EDIT_LEADS, PERMISSIONS.DELETE_LEADS,
    PERMISSIONS.ASSIGN_COUNSELLOR, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.GENERATE_AI_REPORTS,
    PERMISSIONS.USE_AI_STUDIO, PERMISSIONS.MANAGE_PAYMENTS, PERMISSIONS.MANAGE_BATCHES,
    PERMISSIONS.MANAGE_STUDENTS, PERMISSIONS.MANAGE_STAFF, PERMISSIONS.MANAGE_WEBSITE,
    PERMISSIONS.MANAGE_USERS
  ],

  [ROLES.ADMISSION_MANAGER]: [
    PERMISSIONS.VIEW_LEADS, PERMISSIONS.CREATE_LEADS, PERMISSIONS.EDIT_LEADS,
    PERMISSIONS.ASSIGN_COUNSELLOR, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.GENERATE_AI_REPORTS,
    PERMISSIONS.USE_AI_STUDIO, PERMISSIONS.MANAGE_BATCHES, PERMISSIONS.MANAGE_STUDENTS
  ],

  [ROLES.COUNSELLOR]: [
    PERMISSIONS.VIEW_LEADS, PERMISSIONS.CREATE_LEADS, PERMISSIONS.EDIT_LEADS,
    PERMISSIONS.VIEW_REPORTS, PERMISSIONS.GENERATE_AI_REPORTS, PERMISSIONS.USE_AI_STUDIO
  ],

  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.VIEW_LEADS, PERMISSIONS.CREATE_LEADS
  ],

  [ROLES.MARKETING_EXECUTIVE]: [
    PERMISSIONS.VIEW_LEADS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.USE_AI_STUDIO, PERMISSIONS.MANAGE_WEBSITE
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.VIEW_LEADS, PERMISSIONS.MANAGE_PAYMENTS, PERMISSIONS.VIEW_REPORTS
  ],

  [ROLES.GUEST]: [
    PERMISSIONS.CREATE_LEADS
  ]
};

export function hasPermission(role, requiredPermission) {
  if (!role) return false;
  if (role === ROLES.SUPER_ADMIN) return true;
  const permissions = ROLE_PERMISSION_MATRIX[role] || [];
  return permissions.includes(requiredPermission);
}
